---
title: "Parameters Comparison"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: spacelab
    highlight: tango
    toc: true
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
    code_folding: hide
editor_options: 
  chunk_output_type: inline
---


```{r warning=F, message=F, error=F}
rm(list = ls())
source("function.R")
```

# Fit and Test with CV (run once)
```{r warning=F, message=F, error=F}
InD_Dataset = "MNIST"
OOD_Datasets = c("FashionMNIST", "Cifar_10", "SVHN", "Imagenet_r", "Imagenet_c")
model_fit_test(trainset = InD_Dataset, testsets = OOD_Datasets, n_tr = 3000, n_ts = 1000, f = 32)  # Run only once, specify the training samples to use
```

```{r warning=F, message=F, error=F}
InD_Dataset = "FashionMNIST"
OOD_Datasets = c("MNIST", "Cifar_10", "SVHN", "Imagenet_r", "Imagenet_c")
model_fit_test(trainset = InD_Dataset, testsets = OOD_Datasets, n_tr = 3000, n_ts = 1000, f = 32)  # Run only once
```


## MNIST
```{r warning=F, message=F, error=F}
InD_Dataset = "MNIST"
OOD_Datasets = c("FashionMNIST", "Cifar_10", "SVHN", "Imagenet_r", "Imagenet_c")
```

#### KL distance
```{r warning=F, message=F, error=F}
result = score_function(InD_Dataset, OOD_Datasets[1])
hist_plot_KL(result$test.df, result$ood.df, OOD_Datasets[1])

result = score_function(InD_Dataset, OOD_Datasets[2])
hist_plot_KL(result$test.df, result$ood.df, OOD_Datasets[2])

result = score_function(InD_Dataset, OOD_Datasets[3])
hist_plot_KL(result$test.df, result$ood.df, OOD_Datasets[3])

result = score_function(InD_Dataset, OOD_Datasets[4])
hist_plot_KL(result$test.df, result$ood.df, OOD_Datasets[4])

result = score_function(InD_Dataset, OOD_Datasets[5])
hist_plot_KL(result$test.df, result$ood.df, OOD_Datasets[5])
```

#### Mean

```{r warning=F, message=F, error=F}
result = score_function(InD_Dataset, OOD_Datasets[1])
hist_plot_meanSD(result$test.df, result$ood.df, result$cv_results, OOD_Datasets[1], "mean")

result = score_function(InD_Dataset, OOD_Datasets[2])
hist_plot_meanSD(result$test.df, result$ood.df, result$cv_results, OOD_Datasets[2], "mean")

result = score_function(InD_Dataset, OOD_Datasets[3])
hist_plot_meanSD(result$test.df, result$ood.df, result$cv_results, OOD_Datasets[3], "mean")

result = score_function(InD_Dataset, OOD_Datasets[4])
hist_plot_meanSD(result$test.df, result$ood.df, result$cv_results, OOD_Datasets[4], "mean")

result = score_function(InD_Dataset, OOD_Datasets[5])
hist_plot_meanSD(result$test.df, result$ood.df, result$cv_results, OOD_Datasets[5], "mean")
```

#### SD
```{r warning=F, message=F, error=F}
result = score_function(InD_Dataset, OOD_Datasets[1], q = 0.9, f = 16, n_tr = 1000, n_ts = 1000)
hist_plot_meanSD(result$test.df, result$ood.df, result$cv_results, OOD_Datasets[1], "std")

result = score_function(InD_Dataset, OOD_Datasets[2], q = 0.9, f = 16, n_tr = 1000, n_ts = 1000)
hist_plot_meanSD(result$test.df, result$ood.df, result$cv_results, OOD_Datasets[2], "std")

result = score_function(InD_Dataset, OOD_Datasets[3], q = 0.9, f = 16, n_tr = 1000, n_ts = 1000)
hist_plot_meanSD(result$test.df, result$ood.df, result$cv_results, OOD_Datasets[3], "std")

result = score_function(InD_Dataset, OOD_Datasets[4], q = 0.9, f = 16, n_tr = 1000, n_ts = 1000)
hist_plot_meanSD(result$test.df, result$ood.df, result$cv_results, OOD_Datasets[4], "std")

result = score_function(InD_Dataset, OOD_Datasets[5], q = 0.9, f = 16, n_tr = 1000, n_ts = 1000)
hist_plot_meanSD(result$test.df, result$ood.df, result$cv_results, OOD_Datasets[5], "std")
```

#### accuracy

##### feature - 10
```{r warning=F, message=F, error=F}
f = 10

# list5000_0.9_InD = c()
# list5000_0.9_OOD = c()
# for (i in 1:5){
#   pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.9, f = f, n_tr = 5000)
#   list5000_0.9_InD = c(list5000_0.9_InD, pred$ID_all)
#   list5000_0.9_OOD = c(list5000_0.9_OOD, pred$OOD_all)
# }
# 
# list5000_0.8_InD = c()
# list5000_0.8_OOD = c()
# for (i in 1:5){
#   pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.8, f = f, n_tr = 5000)
#   list5000_0.8_InD = c(list5000_0.8_InD, pred$ID_all)
#   list5000_0.8_OOD = c(list5000_0.8_OOD, pred$OOD_all)
# }

list3000_0.9_InD = c()
list3000_0.9_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.9, f = f, n_tr = 3000)
  list3000_0.9_InD = c(list3000_0.9_InD, pred$ID_all)
  list3000_0.9_OOD = c(list3000_0.9_OOD, pred$OOD_all)
}

list3000_0.8_InD = c()
list3000_0.8_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.8, f = f, n_tr = 3000)
  list3000_0.8_InD = c(list3000_0.8_InD, pred$ID_all)
  list3000_0.8_OOD = c(list3000_0.8_OOD, pred$OOD_all)
}

list1000_0.9_InD = c()
list1000_0.9_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.9, f = f, n_tr = 1000)
  list1000_0.9_InD = c(list1000_0.9_InD, pred$ID_all)
  list1000_0.9_OOD = c(list1000_0.9_OOD, pred$OOD_all)
}

list1000_0.8_InD = c()
list1000_0.8_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.8, f = f, n_tr = 1000)
  list1000_0.8_InD = c(list1000_0.8_InD, pred$ID_all)
  list1000_0.8_OOD = c(list1000_0.8_OOD, pred$OOD_all)
}

MNIST = data.frame(
                   # InD5000_0.9 = list5000_0.9_InD, 
                   # OOD5000_0.9 = list5000_0.9_OOD,
                   # InD5000_0.8 = list5000_0.8_InD, 
                   # OOD5000_0.8 = list5000_0.8_OOD,
                   InD3000_0.9 = list3000_0.9_InD, 
                   OOD3000_0.9 = list3000_0.9_OOD,
                   InD3000_0.8 = list3000_0.8_InD, 
                   OOD3000_0.8 = list3000_0.8_OOD,
                   InD1000_0.9 = list1000_0.9_InD, 
                   OOD1000_0.9 = list1000_0.9_OOD,
                   InD1000_0.8 = list1000_0.8_InD, 
                   OOD1000_0.8 = list1000_0.8_OOD)
rownames(MNIST) <- OOD_Datasets
paged_table(MNIST)
```

##### feature - 16
```{r warning=F, message=F, error=F}
f = 16

list3000_0.9_InD = c()
list3000_0.9_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.9, f = f, n_tr = 3000)
  list3000_0.9_InD = c(list3000_0.9_InD, pred$ID_all)
  list3000_0.9_OOD = c(list3000_0.9_OOD, pred$OOD_all)
}

list3000_0.8_InD = c()
list3000_0.8_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.8, f = f, n_tr = 3000)
  list3000_0.8_InD = c(list3000_0.8_InD, pred$ID_all)
  list3000_0.8_OOD = c(list3000_0.8_OOD, pred$OOD_all)
}

list1000_0.9_InD = c()
list1000_0.9_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.9, f = f, n_tr = 1000)
  list1000_0.9_InD = c(list1000_0.9_InD, pred$ID_all)
  list1000_0.9_OOD = c(list1000_0.9_OOD, pred$OOD_all)
}

list1000_0.8_InD = c()
list1000_0.8_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.8, f = f, n_tr = 1000)
  list1000_0.8_InD = c(list1000_0.8_InD, pred$ID_all)
  list1000_0.8_OOD = c(list1000_0.8_OOD, pred$OOD_all)
}

MNIST = data.frame(InD3000_0.9 = list3000_0.9_InD, 
                   OOD3000_0.9 = list3000_0.9_OOD,
                   InD3000_0.8 = list3000_0.8_InD, 
                   OOD3000_0.8 = list3000_0.8_OOD,
                   InD1000_0.9 = list1000_0.9_InD, 
                   OOD1000_0.9 = list1000_0.9_OOD,
                   InD1000_0.8 = list1000_0.8_InD, 
                   OOD1000_0.8 = list1000_0.8_OOD)
rownames(MNIST) <- OOD_Datasets
paged_table(MNIST)
```

##### feature - 18
```{r warning=F, message=F, error=F}
f = 18

list3000_0.9_InD = c()
list3000_0.9_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.9, f = f, n_tr = 3000)
  list3000_0.9_InD = c(list3000_0.9_InD, pred$ID_all)
  list3000_0.9_OOD = c(list3000_0.9_OOD, pred$OOD_all)
}

list3000_0.8_InD = c()
list3000_0.8_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.8, f = f, n_tr = 3000)
  list3000_0.8_InD = c(list3000_0.8_InD, pred$ID_all)
  list3000_0.8_OOD = c(list3000_0.8_OOD, pred$OOD_all)
}

list1000_0.9_InD = c()
list1000_0.9_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.9, f = f, n_tr = 1000)
  list1000_0.9_InD = c(list1000_0.9_InD, pred$ID_all)
  list1000_0.9_OOD = c(list1000_0.9_OOD, pred$OOD_all)
}

list1000_0.8_InD = c()
list1000_0.8_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.8, f = f, n_tr = 1000)
  list1000_0.8_InD = c(list1000_0.8_InD, pred$ID_all)
  list1000_0.8_OOD = c(list1000_0.8_OOD, pred$OOD_all)
}

MNIST = data.frame(InD3000_0.9 = list3000_0.9_InD, 
                   OOD3000_0.9 = list3000_0.9_OOD,
                   InD3000_0.8 = list3000_0.8_InD, 
                   OOD3000_0.8 = list3000_0.8_OOD,
                   InD1000_0.9 = list1000_0.9_InD, 
                   OOD1000_0.9 = list1000_0.9_OOD,
                   InD1000_0.8 = list1000_0.8_InD, 
                   OOD1000_0.8 = list1000_0.8_OOD)
rownames(MNIST) <- OOD_Datasets
paged_table(MNIST)
```


##### feature - 32
```{r warning=F, message=F, error=F}
f = 32

list3000_0.9_InD = c()
list3000_0.9_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.9, f = f, n_tr = 3000)
  list3000_0.9_InD = c(list3000_0.9_InD, pred$ID_all)
  list3000_0.9_OOD = c(list3000_0.9_OOD, pred$OOD_all)
}

list3000_0.8_InD = c()
list3000_0.8_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.8, f = f, n_tr = 3000)
  list3000_0.8_InD = c(list3000_0.8_InD, pred$ID_all)
  list3000_0.8_OOD = c(list3000_0.8_OOD, pred$OOD_all)
}

list1000_0.9_InD = c()
list1000_0.9_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.9, f = f, n_tr = 1000)
  list1000_0.9_InD = c(list1000_0.9_InD, pred$ID_all)
  list1000_0.9_OOD = c(list1000_0.9_OOD, pred$OOD_all)
}

list1000_0.8_InD = c()
list1000_0.8_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.8, f = f, n_tr = 1000)
  list1000_0.8_InD = c(list1000_0.8_InD, pred$ID_all)
  list1000_0.8_OOD = c(list1000_0.8_OOD, pred$OOD_all)
}

MNIST = data.frame(InD3000_0.9 = list3000_0.9_InD, 
                   OOD3000_0.9 = list3000_0.9_OOD,
                   InD3000_0.8 = list3000_0.8_InD, 
                   OOD3000_0.8 = list3000_0.8_OOD,
                   InD1000_0.9 = list1000_0.9_InD, 
                   OOD1000_0.9 = list1000_0.9_OOD,
                   InD1000_0.8 = list1000_0.8_InD, 
                   OOD1000_0.8 = list1000_0.8_OOD)
rownames(MNIST) <- OOD_Datasets
paged_table(MNIST)
```



## FashionMNIST
```{r warning=F, message=F, error=F}
InD_Dataset = "FashionMNIST"
OOD_Datasets = c("MNIST", "Cifar_10", "SVHN", "Imagenet_r", "Imagenet_c")
```

#### KL distance
```{r warning=F, message=F, error=F}
result = score_function(InD_Dataset, OOD_Datasets[1])
hist_plot_KL(result$test.df, result$ood.df, OOD_Datasets[1])

result = score_function(InD_Dataset, OOD_Datasets[2])
hist_plot_KL(result$test.df, result$ood.df, OOD_Datasets[2])

result = score_function(InD_Dataset, OOD_Datasets[3])
hist_plot_KL(result$test.df, result$ood.df, OOD_Datasets[3])

result = score_function(InD_Dataset, OOD_Datasets[4])
hist_plot_KL(result$test.df, result$ood.df, OOD_Datasets[4])

result = score_function(InD_Dataset, OOD_Datasets[5])
hist_plot_KL(result$test.df, result$ood.df, OOD_Datasets[5])
```


#### Mean

```{r warning=F, message=F, error=F}
result = score_function(InD_Dataset, OOD_Datasets[1])
hist_plot_meanSD(result$test.df, result$ood.df, result$cv_results, OOD_Datasets[1], "mean")

result = score_function(InD_Dataset, OOD_Datasets[2])
hist_plot_meanSD(result$test.df, result$ood.df, result$cv_results, OOD_Datasets[2], "mean")

result = score_function(InD_Dataset, OOD_Datasets[3])
hist_plot_meanSD(result$test.df, result$ood.df, result$cv_results, OOD_Datasets[3], "mean")

result = score_function(InD_Dataset, OOD_Datasets[4])
hist_plot_meanSD(result$test.df, result$ood.df, result$cv_results, OOD_Datasets[4], "mean")

result = score_function(InD_Dataset, OOD_Datasets[5])
hist_plot_meanSD(result$test.df, result$ood.df, result$cv_results, OOD_Datasets[5], "mean")
```

#### SD
```{r warning=F, message=F, error=F}
result = score_function(InD_Dataset, OOD_Datasets[1])
hist_plot_meanSD(result$test.df, result$ood.df, result$cv_results, OOD_Datasets[1], "std")

result = score_function(InD_Dataset, OOD_Datasets[2])
hist_plot_meanSD(result$test.df, result$ood.df, result$cv_results, OOD_Datasets[2], "std")

result = score_function(InD_Dataset, OOD_Datasets[3])
hist_plot_meanSD(result$test.df, result$ood.df, result$cv_results, OOD_Datasets[3], "std")

result = score_function(InD_Dataset, OOD_Datasets[4])
hist_plot_meanSD(result$test.df, result$ood.df, result$cv_results, OOD_Datasets[4], "std")

result = score_function(InD_Dataset, OOD_Datasets[5])
hist_plot_meanSD(result$test.df, result$ood.df, result$cv_results, OOD_Datasets[5], "std")
```

#### Acuracy
##### feature - 10
```{r warning=F, message=F, error=F}
f = 10

list3000_0.9_InD = c()
list3000_0.9_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.9, f = f, n_tr = 3000)
  list3000_0.9_InD = c(list3000_0.9_InD, pred$ID_all)
  list3000_0.9_OOD = c(list3000_0.9_OOD, pred$OOD_all)
}

list3000_0.8_InD = c()
list3000_0.8_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.8, f = f, n_tr = 3000)
  list3000_0.8_InD = c(list3000_0.8_InD, pred$ID_all)
  list3000_0.8_OOD = c(list3000_0.8_OOD, pred$OOD_all)
}

list1000_0.9_InD = c()
list1000_0.9_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.9, f = f, n_tr = 1000)
  list1000_0.9_InD = c(list1000_0.9_InD, pred$ID_all)
  list1000_0.9_OOD = c(list1000_0.9_OOD, pred$OOD_all)
}

list1000_0.8_InD = c()
list1000_0.8_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.8, f = f, n_tr = 1000)
  list1000_0.8_InD = c(list1000_0.8_InD, pred$ID_all)
  list1000_0.8_OOD = c(list1000_0.8_OOD, pred$OOD_all)
}

MNIST = data.frame(InD3000_0.9 = list3000_0.9_InD, 
                   OOD3000_0.9 = list3000_0.9_OOD,
                   InD3000_0.8 = list3000_0.8_InD, 
                   OOD3000_0.8 = list3000_0.8_OOD,
                   InD1000_0.9 = list1000_0.9_InD, 
                   OOD1000_0.9 = list1000_0.9_OOD,
                   InD1000_0.8 = list1000_0.8_InD, 
                   OOD1000_0.8 = list1000_0.8_OOD)
rownames(MNIST) <- OOD_Datasets
paged_table(MNIST)
```

##### feature - 16
```{r warning=F, message=F, error=F}
f = 16

list3000_0.9_InD = c()
list3000_0.9_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.9, f = f, n_tr = 3000)
  list3000_0.9_InD = c(list3000_0.9_InD, pred$ID_all)
  list3000_0.9_OOD = c(list3000_0.9_OOD, pred$OOD_all)
}

list3000_0.8_InD = c()
list3000_0.8_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.8, f = f, n_tr = 3000)
  list3000_0.8_InD = c(list3000_0.8_InD, pred$ID_all)
  list3000_0.8_OOD = c(list3000_0.8_OOD, pred$OOD_all)
}

list1000_0.9_InD = c()
list1000_0.9_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.9, f = f, n_tr = 1000)
  list1000_0.9_InD = c(list1000_0.9_InD, pred$ID_all)
  list1000_0.9_OOD = c(list1000_0.9_OOD, pred$OOD_all)
}

list1000_0.8_InD = c()
list1000_0.8_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.8, f = f, n_tr = 1000)
  list1000_0.8_InD = c(list1000_0.8_InD, pred$ID_all)
  list1000_0.8_OOD = c(list1000_0.8_OOD, pred$OOD_all)
}

MNIST = data.frame(InD3000_0.9 = list3000_0.9_InD, 
                   OOD3000_0.9 = list3000_0.9_OOD,
                   InD3000_0.8 = list3000_0.8_InD, 
                   OOD3000_0.8 = list3000_0.8_OOD,
                   InD1000_0.9 = list1000_0.9_InD, 
                   OOD1000_0.9 = list1000_0.9_OOD,
                   InD1000_0.8 = list1000_0.8_InD, 
                   OOD1000_0.8 = list1000_0.8_OOD)
rownames(MNIST) <- OOD_Datasets
paged_table(MNIST)
```


##### feature - 18
```{r warning=F, message=F, error=F}
f = 18

list3000_0.9_InD = c()
list3000_0.9_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.9, f = f, n_tr = 3000)
  list3000_0.9_InD = c(list3000_0.9_InD, pred$ID_all)
  list3000_0.9_OOD = c(list3000_0.9_OOD, pred$OOD_all)
}

list3000_0.8_InD = c()
list3000_0.8_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.8, f = f, n_tr = 3000)
  list3000_0.8_InD = c(list3000_0.8_InD, pred$ID_all)
  list3000_0.8_OOD = c(list3000_0.8_OOD, pred$OOD_all)
}

list1000_0.9_InD = c()
list1000_0.9_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.9, f = f, n_tr = 1000)
  list1000_0.9_InD = c(list1000_0.9_InD, pred$ID_all)
  list1000_0.9_OOD = c(list1000_0.9_OOD, pred$OOD_all)
}

list1000_0.8_InD = c()
list1000_0.8_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.8, f = f, n_tr = 1000)
  list1000_0.8_InD = c(list1000_0.8_InD, pred$ID_all)
  list1000_0.8_OOD = c(list1000_0.8_OOD, pred$OOD_all)
}

MNIST = data.frame(InD3000_0.9 = list3000_0.9_InD, 
                   OOD3000_0.9 = list3000_0.9_OOD,
                   InD3000_0.8 = list3000_0.8_InD, 
                   OOD3000_0.8 = list3000_0.8_OOD,
                   InD1000_0.9 = list1000_0.9_InD, 
                   OOD1000_0.9 = list1000_0.9_OOD,
                   InD1000_0.8 = list1000_0.8_InD, 
                   OOD1000_0.8 = list1000_0.8_OOD)
rownames(MNIST) <- OOD_Datasets
paged_table(MNIST)
```


##### feature - 32
```{r warning=F, message=F, error=F}
f = 32

list3000_0.9_InD = c()
list3000_0.9_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.9, f = f, n_tr = 3000)
  list3000_0.9_InD = c(list3000_0.9_InD, pred$ID_all)
  list3000_0.9_OOD = c(list3000_0.9_OOD, pred$OOD_all)
}

list3000_0.8_InD = c()
list3000_0.8_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.8, f = f, n_tr = 3000)
  list3000_0.8_InD = c(list3000_0.8_InD, pred$ID_all)
  list3000_0.8_OOD = c(list3000_0.8_OOD, pred$OOD_all)
}

list1000_0.9_InD = c()
list1000_0.9_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.9, f = f, n_tr = 1000)
  list1000_0.9_InD = c(list1000_0.9_InD, pred$ID_all)
  list1000_0.9_OOD = c(list1000_0.9_OOD, pred$OOD_all)
}

list1000_0.8_InD = c()
list1000_0.8_OOD = c()
for (i in 1:5){
  pred = score_function(InD_Dataset, OOD_Datasets[i], q = 0.8, f = f, n_tr = 1000)
  list1000_0.8_InD = c(list1000_0.8_InD, pred$ID_all)
  list1000_0.8_OOD = c(list1000_0.8_OOD, pred$OOD_all)
}

MNIST = data.frame(InD3000_0.9 = list3000_0.9_InD, 
                   OOD3000_0.9 = list3000_0.9_OOD,
                   InD3000_0.8 = list3000_0.8_InD, 
                   OOD3000_0.8 = list3000_0.8_OOD,
                   InD1000_0.9 = list1000_0.9_InD, 
                   OOD1000_0.9 = list1000_0.9_OOD,
                   InD1000_0.8 = list1000_0.8_InD, 
                   OOD1000_0.8 = list1000_0.8_OOD)
rownames(MNIST) <- OOD_Datasets
paged_table(MNIST)
```




